# Generated by Django 4.1.3 on 2022-11-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
